import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/material.dart';
import '../../core/models/split_model.dart';
import '../../core/models/transaksi_umkm.dart';
import '../../core/state/transaksi_umkm_store.dart';
import '../../core/utils/currency_formatter.dart';
import '../../core/utils/date_formatter.dart';

final PdfColor _accent = PdfColor(0xFF, 0xCD, 0x00);
final PdfColor _dark = PdfColor(0x1E, 0x1E, 0x1E);
final PdfColor _lightBg = PdfColor(0xFA, 0xFA, 0xFA);
final PdfColor _warmBg = PdfColor(0xFD, 0xFD, 0xF0);
final PdfColor _green = PdfColor(0x22, 0x8B, 0x22);
final PdfColor _stripe = PdfColor(0xF5, 0xF5, 0xF5);

class PdfExportService {
  static Future<Uint8List> _loadLogo() async {
    try {
      final data = await rootBundle.load('assets/icon/icon.png');
      return data.buffer.asUint8List();
    } catch (_) {
      return Uint8List(0);
    }
  }

  static pw.Widget _headerRow(Uint8List logo, String title, String subtitle, pw.Font fontBold) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        if (logo.isNotEmpty) pw.Image(pw.MemoryImage(logo), width: 36, height: 36),
        if (logo.isNotEmpty) pw.SizedBox(width: 12),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title, style: pw.TextStyle(font: fontBold, fontSize: 18, color: _dark)),
              pw.SizedBox(height: 2),
              pw.Text(subtitle, style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.grey600)),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _accentDivider() => pw.Divider(color: _accent, thickness: 2);

  static pw.Widget _footer(pw.Font font) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.center,
      children: [
        pw.Text('Generated by Neobill', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey500)),
      ],
    );
  }

  static pw.Widget _sectionTitle(String text, pw.Font fontBold) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        children: [
          pw.Container(width: 4, height: 16, color: _accent),
          pw.SizedBox(width: 8),
          pw.Text(text, style: pw.TextStyle(font: fontBold, fontSize: 13, color: _dark)),
        ],
      ),
    );
  }

  static pw.Widget _summaryCard(String label, String value, pw.Font font, pw.Font fontBold) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: PdfColors.grey200, width: 0.5),
      ),
      child: pw.Column(
        children: [
          pw.Text(value, style: pw.TextStyle(font: fontBold, fontSize: 14, color: _dark)),
          pw.SizedBox(height: 2),
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  static pw.Widget _summaryRow(String label, String value, pw.Font font, pw.Font fontBold) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(font: fontBold, fontSize: 10, color: _dark)),
        ],
      ),
    );
  }

  static pw.Widget _styledTable({
    required List<String> headers,
    required List<List<String>> data,
    required pw.Font font,
    required pw.Font fontBold,
    Map<int, pw.Alignment>? cellAlignments,
    Map<int, pw.Alignment>? headerAlignments,
  }) {
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(font: fontBold, fontSize: 9, color: PdfColors.white),
      headerDecoration: pw.BoxDecoration(color: _dark),
      headerAlignment: pw.Alignment.centerLeft,
      cellStyle: pw.TextStyle(font: font, fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      cellHeight: 26,
      oddRowDecoration: pw.BoxDecoration(color: _lightBg),
      cellAlignments: cellAlignments,
      headerAlignments: headerAlignments,
      headers: headers,
      data: data,
    );
  }

  static Future<void> exportDailyReport({DateTime? date}) async {
    final d = date ?? DateTime.now();
    final store = TransaksiUmkmStore.instance;
    final transaksi = store.transaksi.where((t) =>
        t.date.year == d.year && t.date.month == d.month && t.date.day == d.day).toList();
    final totalRevenue = transaksi.fold(0.0, (s, t) => s + t.totalAmount);
    final totalProfit = transaksi.fold(0.0, (s, t) => s + t.items.fold(0.0, (si, i) => si + i.profit));

    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoSansRegular();
    final fontBold = await PdfGoogleFonts.nunitoSansBold();
    final logo = await _loadLogo();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => _footer(font),
        header: (context) => pw.Column(
          children: [
            _headerRow(logo, 'Neobill', 'Laporan Harian', fontBold),
            pw.SizedBox(height: 4),
            pw.Text(DateFormatter.formatDate(d), style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
            _accentDivider(),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (context) => [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
            children: [
              _summaryCard('Transaksi', '${transaksi.length}', font, fontBold),
              _summaryCard('Omzet', formatCurrency(totalRevenue), font, fontBold),
              _summaryCard('Profit', formatCurrency(totalProfit), font, fontBold),
            ],
          ),
          pw.SizedBox(height: 20),
          _sectionTitle('Detail Transaksi', fontBold),
          if (transaksi.isEmpty)
            pw.Container(
              padding: const pw.EdgeInsets.all(24),
              alignment: pw.Alignment.center,
              child: pw.Text('Tidak ada transaksi hari ini', style: pw.TextStyle(font: font, color: PdfColors.grey500, fontSize: 10)),
            )
          else
            _styledTable(
              font: font,
              fontBold: fontBold,
              headers: ['Waktu', 'Merchant', 'Items', 'Bayar', 'Total'],
              data: transaksi.map((t) => [
                '${t.date.hour.toString().padLeft(2, '0')}:${t.date.minute.toString().padLeft(2, '0')}',
                t.merchantName,
                '${t.items.length}',
                paymentMethodName(t.paymentMethod),
                formatCurrency(t.totalAmount),
              ]).toList(),
            ),

          pw.SizedBox(height: 20),
          _sectionTitle('Top Items Hari Ini', fontBold),
          ...store.topItems(limit: 5).asMap().entries.map((entry) => pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 8),
            decoration: pw.BoxDecoration(
              color: entry.key.isEven ? _lightBg : PdfColors.white,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Row(
                  children: [
                    pw.Container(
                      width: 20, height: 20,
                      alignment: pw.Alignment.center,
                      decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(10)),
                      child: pw.Text('${entry.key + 1}', style: pw.TextStyle(font: fontBold, fontSize: 8, color: PdfColors.white)),
                    ),
                    pw.SizedBox(width: 8),
                    pw.Text(entry.value.name, style: pw.TextStyle(font: font, fontSize: 10)),
                  ],
                ),
                pw.Text('${entry.value.qty}x  •  ${formatCurrency(entry.value.revenue)}',
                    style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.grey700)),
              ],
            ),
          )),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Laporan Neobill ${d.day}-${d.month}-${d.year}',
    );
  }

  static Future<void> exportAllTransactions({DateTimeRange? range}) async {
    final store = TransaksiUmkmStore.instance;
    List<TransaksiUmkm> transaksi;
    String title;

    if (range != null) {
      transaksi = store.transactionsInRange(range.start, range.end);
      title = 'Transaksi ${range.start.day}/${range.start.month} – ${range.end.day}/${range.end.month}';
    } else {
      transaksi = store.transaksi;
      title = 'Semua Transaksi';
    }

    final totalRevenue = transaksi.fold(0.0, (s, t) => s + t.totalAmount);

    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoSansRegular();
    final fontBold = await PdfGoogleFonts.nunitoSansBold();
    final logo = await _loadLogo();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => _footer(font),
        header: (context) => pw.Column(
          children: [
            _headerRow(logo, 'Neobill', title, fontBold),
            pw.SizedBox(height: 4),
            pw.Text('${transaksi.length} transaksi  •  Total: ${formatCurrency(totalRevenue)}',
                style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
            _accentDivider(),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (context) => [
          _styledTable(
            font: font,
            fontBold: fontBold,
            headers: ['Tanggal', 'Merchant', 'Items', 'Kategori', 'Bayar', 'Total'],
            data: transaksi.map((t) => [
              '${t.date.day}/${t.date.month}',
              t.merchantName,
              '${t.items.length}',
              t.category,
              paymentMethodName(t.paymentMethod),
              formatCurrency(t.totalAmount),
            ]).toList(),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Neobill $title',
    );
  }

  static Future<void> exportSplitBill(SplitBill splitBill) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoSansRegular();
    final fontBold = await PdfGoogleFonts.nunitoSansBold();
    final logo = await _loadLogo();

    final memberItemMap = <String, List<ReceiptItem>>{};
    for (final member in splitBill.members) {
      memberItemMap[member.id] = splitBill.items
          .where((i) =>
              i.assignedMemberIds.contains(member.id) ||
              i.assignedMemberIds.isEmpty)
          .toList();
    }

    double itemShare(ReceiptItem item) {
      final count = item.assignedMemberIds.isEmpty
          ? splitBill.members.length
          : item.assignedMemberIds.length;
      return count > 0 ? item.lineTotal / count : 0;
    }

    double memberSubtotal(Member member) {
      return (memberItemMap[member.id] ?? []).fold(0.0, (sum, i) => sum + itemShare(i));
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => _footer(font),
        header: (context) => pw.Column(
          children: [
            _headerRow(logo, 'Neobill', splitBill.title, fontBold),
            pw.SizedBox(height: 4),
            pw.Text(DateFormatter.formatDate(splitBill.date),
                style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
            _accentDivider(),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              borderRadius: pw.BorderRadius.circular(8),
              border: pw.Border.all(color: PdfColors.grey200, width: 0.5),
            ),
            child: pw.Column(
              children: [
                _summaryRow('Subtotal', formatCurrency(splitBill.subtotal), font, fontBold),
                if (splitBill.tax > 0) _summaryRow('Pajak', formatCurrency(splitBill.tax), font, font),
                if (splitBill.serviceCharge > 0) _summaryRow('Service', formatCurrency(splitBill.serviceCharge), font, font),
                if (splitBill.discount > 0) _summaryRow('Diskon', '-${formatCurrency(splitBill.discount)}', font, font),
                pw.Divider(color: PdfColors.grey300),
                _summaryRow('Total Tagihan', formatCurrency(splitBill.totalAmount), font, fontBold),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          ...splitBill.members.map((member) {
            final items = memberItemMap[member.id] ?? [];
            final subtotal = memberSubtotal(member);
            final taxShare = (member.amountOwed - subtotal).clamp(0.0, double.infinity).toDouble();

            return pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 16),
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: PdfColors.white,
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: PdfColors.grey200, width: 0.5),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Row(
                    children: [
                      pw.Container(
                        width: 28, height: 28,
                        alignment: pw.Alignment.center,
                        decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(14)),
                        child: pw.Text(member.name.isNotEmpty ? member.name[0].toUpperCase() : '?',
                            style: pw.TextStyle(font: fontBold, fontSize: 12, color: PdfColors.white)),
                      ),
                      pw.SizedBox(width: 10),
                      pw.Expanded(
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text(member.name, style: pw.TextStyle(font: fontBold, fontSize: 12, color: _dark)),
                            pw.Text(
                              member.isPaid ? 'Lunas' : 'Belum Bayar',
                              style: pw.TextStyle(font: font, fontSize: 8, color: member.isPaid ? _green : PdfColors.grey500),
                            ),
                          ],
                        ),
                      ),
                      pw.Text(formatCurrency(member.amountOwed),
                          style: pw.TextStyle(font: fontBold, fontSize: 13, color: _dark)),
                    ],
                  ),
                  pw.SizedBox(height: 10),
                  pw.TableHelper.fromTextArray(
                    headerStyle: pw.TextStyle(font: fontBold, fontSize: 8, color: PdfColors.white),
                    headerDecoration: pw.BoxDecoration(color: PdfColors.grey600),
                    cellStyle: pw.TextStyle(font: font, fontSize: 8),
                    cellHeight: 22,
                    headerAlignment: pw.Alignment.centerLeft,
                    cellAlignment: pw.Alignment.centerLeft,
                    oddRowDecoration: pw.BoxDecoration(color: _stripe),
                    headers: ['Item', 'Qty', 'Harga', 'Subtotal'],
                    data: items.map((item) => [
                      item.name,
                      '${item.quantity}',
                      formatCurrency(item.price),
                      formatCurrency(itemShare(item)),
                    ]).toList(),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                    decoration: pw.BoxDecoration(
                      color: _warmBg,
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                    child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Subtotal', style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
                        pw.Text(formatCurrency(subtotal), style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
                      ],
                    ),
                  ),
                  if (taxShare > 0)
                    pw.Container(
                      margin: const pw.EdgeInsets.only(top: 2),
                      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                      decoration: pw.BoxDecoration(
                        color: _warmBg,
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text('Pajak & Service', style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
                          pw.Text(formatCurrency(taxShare), style: pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey700)),
                        ],
                      ),
                    ),
                ],
              ),
            );
          }),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'neobill_${splitBill.title}.pdf');
  }
}
